/**
 * Den Web API types — split by service domain.
 *
 * Re-exports everything from the split API type modules for backward compatibility.
 * New code should import from the specific type module:
 *   - `@api/core/types`     — Spaces, Projects, Tasks, Messages, Documents, Stream, Git, etc.
 *   - `@api/channels/types`  — Channel, ChannelMessage, ChannelReactionSummary, etc.
 *   - `@api/gateway/types`  — Channels gateway helpers, agents overview, Den Host FleetOps
 */

// === Core types ===
export type {
  TaskStatus,
  DocType,
  MessageIntent,
  AgentStreamKind,
  AgentStreamDeliveryMode,
  DispatchStatus,
  DispatchTriggerType,
  ReviewVerdict,
  ReviewFindingCategory,
  ReviewFindingStatus,
  ReviewPacketKind,
  AgentWorkspaceState,
  AgentWorkspaceCleanupPolicy,
  DesktopSessionEventType,
  SpaceKind,
  SpaceVisibility,
} from './core/types';
export type {
  Space,
  Project,
  ProjectWithStats,
  ProjectTask,
  TaskSummary,
  TaskDependencyInfo,
  TaskDetail,
  ReviewRound,
  ReviewDiffRange,
  ReviewBranchComposition,
  ReviewFinding,
  ReviewWorkflowSummary,
  ReviewTimelineEntry,
  ReviewPacket,
  ReviewPacketResult,
  Message,
  Thread,
  Document,
  DocumentSummary,
  DocumentSearchResult,
  LibrarianConfidence,
  RelevantItem,
  LibrarianResponse,
  AgentStreamEntry,
  SubagentRunState,
  SubagentRunSummary,
  SubagentRunUsageSummary,
  SubagentRunEventCounts,
  SubagentRunOperatorEvent,
  SubagentRunDetail,
  SubagentRunWorkEvent,
  SubagentRunArtifactSnapshot,
  AttentionItem,
  DispatchEntry,
  AgentWorkspace,
  GitDirtyCounts,
  GitFileStatus,
  GitStatusResponse,
  GitFilesResponse,
  GitDiffResponse,
  DesktopSnapshotState,
  DesktopGitSnapshot,
  DesktopGitSnapshotLatestResult,
  DesktopDiffSnapshot,
  DesktopDiffSnapshotLatestResult,
  DesktopSessionSnapshot,
  DesktopSessionEvent,
  AppendDesktopSessionEventRequest,
  ListDesktopSessionEventsOptions,
  DiscussionComment,
  DocumentDiscussion,
  NotificationFeedItem,
  StaleWorkerCondition,
  StaleWorkerSweepResponse,
} from './core/types';

// === Channels types ===
export type {
  Channel,
  ChannelProjectLink,
  ChannelMessage,
  ChannelReactionSummary,
  ChannelActivityEvent,
  AgentWorkCurrentItem,
  AgentWorkCurrentResponse,
  AgentWorkLifecycleEvent,
  AgentWorkEventsResponse,
  DirectAgentEvent,
  DirectAgentEventsResponse,
  ChannelWakePolicy,
  ActiveWorkRoute,
  ActiveWorkRouteHandles,
  ActiveWorkRouteEvidence,
  ActiveWorkRouteSourceEvidence,
  ActiveWorkRoutesResponse,
  ActiveWorkRouteResponse,
} from './channels/types';

// === Gateway types ===
export type {
  GatewayMember,
  GatewayMemberships,
  PostGatewayDirectAgentMessageRequest,
  GatewayDirectAgentMessage,
  UpsertChannelMembershipRequest,
  AgentsOverviewRequest,
  AgentsOverviewResponse,
  SourceHealthDto,
  SourceServiceStatusDto,
  AgentOverviewItem,
  AgentSummaryDto,
  AgentLinksDto,
  ChannelMembershipOverviewDto,
  GatewayBindingOverviewDto,
  GatewayDeliveryCountsDto,
  GatewayAdapterInstanceDto,
  DeliveryOverviewDto,
  ActivityEventOverviewDto,
  AgentDetailResponse,
  TaskAssociationDto,
  AssignmentTraceResponse,
  AssignmentCoreState,
  AssignmentCheckpointDto,
  AssignmentGatewayEvidence,
  TraceSourceAvailability,
  WorkerPoolMemberPresence,
  WorkerPoolAvailabilityState,
  WorkerPoolLobbyPresence,
  FleetOpsServiceUnit,
  FleetOpsActionArgSchema,
  FleetOpsAction,
  FleetOpsActionRun,
  FleetOpsResponse,
  FleetOpsActionRunRequest,
  FleetOpsActionRunResponse,
  FleetOpsRunDetailResponse,
} from './gateway/types';
